# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NzRjMjI3ZDgzYWI3YmM5MjkwMzY0NmFhMzkzMGIwMmZjOWM3NTRiMGFmYzFmNjRmNWU2MjkzNDZmMzAyZjRlYTYyN2YyYjNlNTM2MDRhNGM1NDE1NzVkZGFmZThiZDAyNGQ3Y2NhZWQ5MWUxNzNkMmE3MTI1YWMyZDYwNTYxOTQ=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: postgres
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: brahim
    password: '123456'
