package com.gestiontaches.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ActionHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActionHistoryAllPropertiesEquals(ActionHistory expected, ActionHistory actual) {
        assertActionHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertActionHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActionHistoryAllUpdatablePropertiesEquals(ActionHistory expected, ActionHistory actual) {
        assertActionHistoryUpdatableFieldsEquals(expected, actual);
        assertActionHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActionHistoryAutoGeneratedPropertiesEquals(ActionHistory expected, ActionHistory actual) {
        assertThat(actual)
            .as("Verify ActionHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActionHistoryUpdatableFieldsEquals(ActionHistory expected, ActionHistory actual) {
        assertThat(actual)
            .as("Verify ActionHistory relevant properties")
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getFieldChanged()).as("check fieldChanged").isEqualTo(expected.getFieldChanged()))
            .satisfies(a -> assertThat(a.getOldValue()).as("check oldValue").isEqualTo(expected.getOldValue()))
            .satisfies(a -> assertThat(a.getNewValue()).as("check newValue").isEqualTo(expected.getNewValue()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActionHistoryUpdatableRelationshipsEquals(ActionHistory expected, ActionHistory actual) {
        assertThat(actual)
            .as("Verify ActionHistory relationships")
            .satisfies(a -> assertThat(a.getIssue()).as("check issue").isEqualTo(expected.getIssue()));
    }
}
